resolver: lts-14.16


ghc-options:
  $locals: -O2 -Wall -Wno-missing-signatures -threaded -rtsopts -with-rtsopts=-N

packages:
  - day01
  - day02
  - day03
  - day04
  - day05
  - day06
  - day07
  - day08
  - day09
