# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.

name: day04
synopsis: Advent of Code
version: '0.0.1'

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImplicitParams
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MonoLocalBinds
  - MultiParamTypeClasses
  - MultiWayIf
  - NegativeLiterals
  - NumDecimals
  - OverloadedLists
  - PartialTypeSignatures
  - PatternGuards
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TransformListComp
  - TupleSections
  - TypeApplications
  - TypeInType
  - TypeOperators
  - ViewPatterns


executables:
  day04:
    main: day04.hs
    source-dirs: src
    dependencies:
      - base >= 2 && < 6
      - text
      - megaparsec
      - containers
      - tasty
      - tasty-hspec
